/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.qlbh.view;

import com.qlbh.dao.NhanVienDAO;
import com.qlbh.dao.UserDAO;
import com.qlbh.model.User;
import com.qlbh.tools.MD5;
import java.awt.Color;
import java.util.ArrayList;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author HoangDucTung
 */
public class AccountManager extends javax.swing.JFrame {

    /**
     * Creates new form AccountManager
     */
    DefaultTableModel userTableModel;
    ImageIcon sai = new ImageIcon("tinhsai.png");
    ImageIcon dung = new ImageIcon("dau-check.png");
    private String username ;

    public String getUsername() {
        return username;
    }

    public void setUsername(String username) {
        System.out.println(username);
        this.username = username;
    }
    
    public AccountManager(String username) {
        initComponents();
        AccountManager.super.setLocationRelativeTo(null);
        userTableModel = (DefaultTableModel) userjTable.getModel();
        loadAllUser();
        huyUserjButton.setEnabled(false);
        System.out.println(username);
        welcome.setText(username);
    }

    
    

    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        userjTable = new javax.swing.JTable();
        jLabel5 = new javax.swing.JLabel();
        usernamejTextField = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        rolejComboBox = new javax.swing.JComboBox<>();
        passwordjPasswordField = new javax.swing.JPasswordField();
        themUserjButton = new javax.swing.JButton();
        xoaUserjButton = new javax.swing.JButton();
        huyUserjButton = new javax.swing.JButton();
        nhanVienjLabel = new javax.swing.JLabel();
        welcome = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Quản lí tài khoản");
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(247, 255, 247));

        jLabel1.setBackground(new java.awt.Color(78, 205, 196));
        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 230, 109));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("QUẢN LÍ TÀI KHOẢN");
        jLabel1.setOpaque(true);

        userjTable.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        userjTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "STT", "Username", "Password", "Role"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, true, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        userjTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                userjTableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(userjTable);
        if (userjTable.getColumnModel().getColumnCount() > 0) {
            userjTable.getColumnModel().getColumn(0).setResizable(false);
            userjTable.getColumnModel().getColumn(1).setResizable(false);
            userjTable.getColumnModel().getColumn(2).setResizable(false);
            userjTable.getColumnModel().getColumn(3).setResizable(false);
        }

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel5.setText("Username");

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel6.setText("Password");

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel7.setText("Role");

        rolejComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { " ", "Nhân viên", "Quản lí" }));

        passwordjPasswordField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                passwordjPasswordFieldActionPerformed(evt);
            }
        });

        themUserjButton.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        themUserjButton.setText("THÊM");
        themUserjButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                themUserjButtonActionPerformed(evt);
            }
        });

        xoaUserjButton.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        xoaUserjButton.setText("XÓA");
        xoaUserjButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                xoaUserjButtonActionPerformed(evt);
            }
        });

        huyUserjButton.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        huyUserjButton.setText("HỦY");
        huyUserjButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                huyUserjButtonActionPerformed(evt);
            }
        });

        nhanVienjLabel.setBackground(new java.awt.Color(255, 107, 107));
        nhanVienjLabel.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        nhanVienjLabel.setForeground(new java.awt.Color(247, 255, 247));
        nhanVienjLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        nhanVienjLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/qlbh/images/employee.png"))); // NOI18N
        nhanVienjLabel.setText("NHÂN VIÊN");
        nhanVienjLabel.setOpaque(true);
        nhanVienjLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                nhanVienjLabelMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                nhanVienjLabelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                nhanVienjLabelMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                nhanVienjLabelMousePressed(evt);
            }
        });

        welcome.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        welcome.setForeground(new java.awt.Color(153, 0, 0));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(390, 390, 390)
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 312, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(51, 51, 51)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(20, 20, 20)
                                        .addComponent(usernamejTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(nhanVienjLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(50, 50, 50)
                                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(passwordjPasswordField, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(50, 50, 50)
                                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(20, 20, 20))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                        .addComponent(themUserjButton, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(53, 53, 53)
                                        .addComponent(xoaUserjButton, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(53, 53, 53)))
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(huyUserjButton, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(rolejComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(0, 51, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(welcome, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(19, 19, 19))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(welcome, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(8, 8, 8)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 406, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(usernamejTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(rolejComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(passwordjPasswordField, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(65, 65, 65)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(themUserjButton, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(xoaUserjButton, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(huyUserjButton, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(nhanVienjLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(84, Short.MAX_VALUE))
        );

        jMenu1.setText("File");
        jMenuBar1.add(jMenu1);

        jMenu2.setText("Edit");
        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public void loadAllUser() {
        ArrayList<User> listUser = UserDAO.getListUser();
        for (int i = 0; i < listUser.size(); i++) {
            userTableModel.addRow(new Object[]{
                i + 1, listUser.get(i).getMaNhanVien(), listUser.get(i).getPassword(), listUser.get(i).getRole() == 1 ? "Nhân viên" : "Quản lí"
            });
        }
    }


    private void passwordjPasswordFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_passwordjPasswordFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_passwordjPasswordFieldActionPerformed

    private void themUserjButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_themUserjButtonActionPerformed
        // TODO add your handling code here:
        try {
            String username = usernamejTextField.getText();
            if (NhanVienDAO.kiemTraMaNhanVienDaTonTai(username)) {
                String password = String.valueOf(passwordjPasswordField.getPassword());
                String hashPassword = MD5.md5(password);
                String roleString = rolejComboBox.getSelectedItem().toString();
                int role = 0;
                if (roleString.equals("Nhân viên")) {
                    role = 1;
                } else if (roleString.equals("Quản lí")) {
                    role = 2;
                }
                User user = new User(null, username, hashPassword, role);
                if (UserDAO.kiemTraUsernameTonTai(username)) {
                    JOptionPane.showMessageDialog(null, "Username đã tồn tại", "Message", JOptionPane.INFORMATION_MESSAGE, sai);
                } else {
                    if (UserDAO.themUser(user)) {
                        int rowCount = userTableModel.getRowCount();
                        userTableModel.addRow(new Object[]{
                            rowCount+1, user.getMaNhanVien(),user.getPassword(),user.getRole()==1? "Nhân viên" : "Quản lí"
                        });
                        JOptionPane.showMessageDialog(null, "Đã thêm user", "Message", JOptionPane.INFORMATION_MESSAGE, dung);

                    } else {
                        JOptionPane.showMessageDialog(null, "Có lỗi xảy ra, thử lại sai", "Message", JOptionPane.INFORMATION_MESSAGE, sai);

                    }
                }
            } else {
                JOptionPane.showMessageDialog(null, "Vui lòng thêm nhân viên trước khi tạo tài khoản", "Message", JOptionPane.INFORMATION_MESSAGE, sai);
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Kiểm tra thông tin nhập vào", "Message", JOptionPane.INFORMATION_MESSAGE, sai);

        }
        passwordjPasswordField.setText("");
        usernamejTextField.setText("");
        rolejComboBox.removeAllItems();
        rolejComboBox.addItem("");
        rolejComboBox.addItem("Nhân viên");
        rolejComboBox.addItem("Quản lí");
    }//GEN-LAST:event_themUserjButtonActionPerformed

    private void nhanVienjLabelMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_nhanVienjLabelMousePressed
        // TODO add your handling code here:

    }//GEN-LAST:event_nhanVienjLabelMousePressed

    private void nhanVienjLabelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_nhanVienjLabelMouseEntered
        // TODO add your handling code here:
        nhanVienjLabel.setBackground(new Color(78, 205, 196));
    }//GEN-LAST:event_nhanVienjLabelMouseEntered

    private void nhanVienjLabelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_nhanVienjLabelMouseExited
        // TODO add your handling code here:
        nhanVienjLabel.setBackground(new Color(255, 107, 107));
    }//GEN-LAST:event_nhanVienjLabelMouseExited

    private void userjTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_userjTableMouseClicked
        // TODO add your handling code here:
        int row = userjTable.getSelectedRow();
        passwordjPasswordField.setText(userTableModel.getValueAt(row, 2).toString());
        usernamejTextField.setText(userTableModel.getValueAt(row, 1).toString());
        rolejComboBox.removeAllItems();
        rolejComboBox.addItem(userTableModel.getValueAt(row, 3).toString());
        if (userTableModel.getValueAt(row, 3).toString().equals("Nhân viên")) {
            rolejComboBox.addItem("Quản lí");
        } else {
            rolejComboBox.addItem("Nhân viên");
        }
        themUserjButton.setEnabled(false);
        huyUserjButton.setEnabled(true);
    }//GEN-LAST:event_userjTableMouseClicked

    private void xoaUserjButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_xoaUserjButtonActionPerformed
        // TODO add your handling code here:
        int row = userjTable.getSelectedRow();
        if (row != -1) {
            String username = usernamejTextField.getText();

            int luaChon = JOptionPane.showConfirmDialog(null, "Bạn có chắn chắn muốn xóa không", "Message", JOptionPane.YES_NO_OPTION);
            if (luaChon == JOptionPane.YES_OPTION) {
                if (UserDAO.xoaUser(username)) {
                    passwordjPasswordField.setText("");
                    usernamejTextField.setText("");
                    rolejComboBox.removeAllItems();
                    rolejComboBox.addItem("");
                    rolejComboBox.addItem("Nhân viên");
                    rolejComboBox.addItem("Quản lí");
                    themUserjButton.setEnabled(true);
                    huyUserjButton.setEnabled(false);
                    userTableModel.removeRow(row);
                    JOptionPane.showMessageDialog(null, "Đã xóa", "Message", JOptionPane.INFORMATION_MESSAGE, dung);

                } else {
                    JOptionPane.showMessageDialog(null, "Có lỗi xảy ra, thử lại sau", "Message", JOptionPane.INFORMATION_MESSAGE, sai);

                }
            } else if (luaChon == JOptionPane.NO_OPTION) {

                JOptionPane.showMessageDialog(null, "Đã hủy việc xóa", "Message", JOptionPane.INFORMATION_MESSAGE, sai);
            }
        } else {
            JOptionPane.showMessageDialog(null, "chọn một hàng để xóa", "Message", JOptionPane.INFORMATION_MESSAGE, sai);

        }

    }//GEN-LAST:event_xoaUserjButtonActionPerformed

    private void huyUserjButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_huyUserjButtonActionPerformed
        // TODO add your handling code here:
        passwordjPasswordField.setText("");
        usernamejTextField.setText("");
        rolejComboBox.removeAllItems();
        rolejComboBox.addItem("");
        rolejComboBox.addItem("Nhân viên");
        rolejComboBox.addItem("Quản lí");
        themUserjButton.setEnabled(true);
        huyUserjButton.setEnabled(false);
    }//GEN-LAST:event_huyUserjButtonActionPerformed

    private void nhanVienjLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_nhanVienjLabelMouseClicked
        // TODO add your handling code here:
        NhanVienJFrame nhanVienJFrame = new NhanVienJFrame();
        nhanVienJFrame.setLocationRelativeTo(null);
        nhanVienJFrame.setResizable(false);
        nhanVienJFrame.setVisible(true);
//        nhanVienJFrame.pack();
//        nhanVienJFrame.setDefaultCloseOperation(EXIT_ON_CLOSE);
        this.dispose();
    }//GEN-LAST:event_nhanVienjLabelMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AccountManager.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AccountManager.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AccountManager.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AccountManager.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AccountManager().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton huyUserjButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel nhanVienjLabel;
    private javax.swing.JPasswordField passwordjPasswordField;
    private javax.swing.JComboBox<String> rolejComboBox;
    private javax.swing.JButton themUserjButton;
    private javax.swing.JTable userjTable;
    private javax.swing.JTextField usernamejTextField;
    private javax.swing.JLabel welcome;
    private javax.swing.JButton xoaUserjButton;
    // End of variables declaration//GEN-END:variables
}
