/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.qlbh.view;

import com.qlbh.dao.BieuDoNhanVienDAO;
import com.qlbh.dao.BieuDoSanPhamDAO;
import com.qlbh.model.BieuDoNhanVien;
import com.qlbh.model.BieuDoSanPham;
import java.awt.CardLayout;
import java.awt.Dimension;
import java.util.ArrayList;
import org.jfree.chart.ChartFactory;
import org.jfree.chart.ChartPanel;
import org.jfree.chart.JFreeChart;
import org.jfree.chart.plot.PlotOrientation;
import org.jfree.data.category.DefaultCategoryDataset;

/**
 *
 * @author HoangDucTung
 */
public class BieuDoJPanel extends javax.swing.JPanel {

    /**
     * Creates new form NhanVienJPanel
     */
    public BieuDoJPanel(String username) {
        initComponents();
        loadBieuDoSanPham();
        loadBieuDoNhanVien();
    }

    public void loadBieuDoSanPham() {
        ArrayList<BieuDoSanPham> listBieuDoSP = BieuDoSanPhamDAO.getListBieuDoSanPham();
        DefaultCategoryDataset dataset = new DefaultCategoryDataset();
        if (listBieuDoSP != null) {
            for (BieuDoSanPham sanPham : listBieuDoSP) {
                dataset.addValue(sanPham.getSoLuongBan(), "Sản phẩm", sanPham.getMaSanPham());
            }
        }

        JFreeChart barChart = ChartFactory.createBarChart("Biểu đồ thống kê số lượng sản phẩm bán ra".toUpperCase(),
                "Mã sản phẩm", "Số lượng", dataset, PlotOrientation.VERTICAL, false, true, true);
        ChartPanel chartPanel = new ChartPanel(barChart);
        chartPanel.setPreferredSize(new Dimension(bieuDoSanPhamjPanel.getWidth(), 321));
        bieuDoSanPhamjPanel.removeAll();
        bieuDoSanPhamjPanel.setLayout(new CardLayout());
        bieuDoSanPhamjPanel.add(chartPanel);
        bieuDoSanPhamjPanel.validate();
        bieuDoSanPhamjPanel.repaint();
    }

    public void loadBieuDoNhanVien() {
        ArrayList<BieuDoNhanVien> listBieuDoNV = BieuDoNhanVienDAO.getListBieuDoNhanVien();
        DefaultCategoryDataset dataset = new DefaultCategoryDataset();
        if (listBieuDoNV != null) {
            for (BieuDoNhanVien nhanVien : listBieuDoNV) {
                dataset.addValue(nhanVien.getSoLuongHoaDon(), "Nhân viên", nhanVien.getMaNhanVien());
            }
        }

        JFreeChart barChart = ChartFactory.createBarChart("Biểu đồ thống kê 5 nhân viên có hóa đơn nhiều nhất".toUpperCase(),
                "Mã nhân viên", "Số lượng hóa đơn", dataset, PlotOrientation.VERTICAL, false, true, true);
        ChartPanel chartPanel = new ChartPanel(barChart);
        chartPanel.setPreferredSize(new Dimension(bieuDoNhanVienjPanel.getWidth(), 321));
        bieuDoNhanVienjPanel.removeAll();
        bieuDoNhanVienjPanel.setLayout(new CardLayout());
        bieuDoNhanVienjPanel.add(chartPanel);
        bieuDoNhanVienjPanel.validate();
        bieuDoNhanVienjPanel.repaint();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bieuDoSanPhamjPanel = new javax.swing.JPanel();
        bieuDoNhanVienjPanel = new javax.swing.JPanel();

        setBackground(new java.awt.Color(0, 102, 102));

        javax.swing.GroupLayout bieuDoSanPhamjPanelLayout = new javax.swing.GroupLayout(bieuDoSanPhamjPanel);
        bieuDoSanPhamjPanel.setLayout(bieuDoSanPhamjPanelLayout);
        bieuDoSanPhamjPanelLayout.setHorizontalGroup(
            bieuDoSanPhamjPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1422, Short.MAX_VALUE)
        );
        bieuDoSanPhamjPanelLayout.setVerticalGroup(
            bieuDoSanPhamjPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 380, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout bieuDoNhanVienjPanelLayout = new javax.swing.GroupLayout(bieuDoNhanVienjPanel);
        bieuDoNhanVienjPanel.setLayout(bieuDoNhanVienjPanelLayout);
        bieuDoNhanVienjPanelLayout.setHorizontalGroup(
            bieuDoNhanVienjPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        bieuDoNhanVienjPanelLayout.setVerticalGroup(
            bieuDoNhanVienjPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bieuDoSanPhamjPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(bieuDoNhanVienjPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(bieuDoSanPhamjPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(0, 0, 0)
                .addComponent(bieuDoNhanVienjPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel bieuDoNhanVienjPanel;
    private javax.swing.JPanel bieuDoSanPhamjPanel;
    // End of variables declaration//GEN-END:variables
}
