/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.qlbh.view;

import com.qlbh.dao.KhachHangDAO;
import com.qlbh.model.KhachHang;
import java.util.ArrayList;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author HoangDucTung
 */
public class KhachHangJPanel extends javax.swing.JPanel {

    /**
     * Creates new form KhachHangJPanel
     */
    DefaultTableModel khachHangtableModel;
    ImageIcon sai = new ImageIcon("tinhsai.png");
    ImageIcon dung = new ImageIcon("dau-check.png");

    public KhachHangJPanel(String username) {
        initComponents();
        khachHangtableModel = (DefaultTableModel) khachHangjTable.getModel();
        ArrayList<KhachHang> listKhachHang = KhachHangDAO.getListKhachHang();
        for (KhachHang khachHang : listKhachHang) {
            khachHangtableModel.addRow(new Object[]{
                khachHang.getMaKhachHang(), khachHang.getTenKhachHang(), khachHang.getEmailKhachHang(), khachHang.getDiaChiKhachHang(), khachHang.getSoDienThoaiKH()
            });
        }
        setEnabledButton();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        khachHangjTable = new javax.swing.JTable();
        tenKhachHangjLabel = new javax.swing.JLabel();
        diaChiKhachHangjLabel = new javax.swing.JLabel();
        emailKhachHangjLabel = new javax.swing.JLabel();
        maKhachHangjLabel = new javax.swing.JLabel();
        soDienThoaiKhachHangjLabel = new javax.swing.JLabel();
        hoTenKhachHangjTextField = new javax.swing.JTextField();
        diaChiKhachHangjTextField = new javax.swing.JTextField();
        soDienThoaiKhachHangjTextField = new javax.swing.JTextField();
        maKhachHangjTextField = new javax.swing.JTextField();
        emailKhachHangjTextField = new javax.swing.JTextField();
        huyKhachHangjButton = new javax.swing.JButton();
        nhapKhachHangjButton = new javax.swing.JButton();
        themKhachHangjButton = new javax.swing.JButton();
        xuatKhachHangjButton = new javax.swing.JButton();
        xoaKhachHangjButton = new javax.swing.JButton();
        suaKhachHangjButton = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(0, 102, 102));

        jLabel1.setFont(new java.awt.Font("Arial", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("KHÁCH HÀNG");

        khachHangjTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Mã khách hàng", "Tên khách hàng", "Địa chỉ", "Số điện thoại", "Email"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        khachHangjTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                khachHangjTableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(khachHangjTable);
        if (khachHangjTable.getColumnModel().getColumnCount() > 0) {
            khachHangjTable.getColumnModel().getColumn(0).setResizable(false);
            khachHangjTable.getColumnModel().getColumn(1).setResizable(false);
            khachHangjTable.getColumnModel().getColumn(2).setResizable(false);
            khachHangjTable.getColumnModel().getColumn(3).setResizable(false);
            khachHangjTable.getColumnModel().getColumn(4).setResizable(false);
        }

        tenKhachHangjLabel.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        tenKhachHangjLabel.setForeground(new java.awt.Color(255, 255, 255));
        tenKhachHangjLabel.setText("Họ tên");

        diaChiKhachHangjLabel.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        diaChiKhachHangjLabel.setForeground(new java.awt.Color(255, 255, 255));
        diaChiKhachHangjLabel.setText("Địa chỉ");

        emailKhachHangjLabel.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        emailKhachHangjLabel.setForeground(new java.awt.Color(255, 255, 255));
        emailKhachHangjLabel.setText("Email");

        maKhachHangjLabel.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        maKhachHangjLabel.setForeground(new java.awt.Color(255, 255, 255));
        maKhachHangjLabel.setText("Mã khách hàng");

        soDienThoaiKhachHangjLabel.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        soDienThoaiKhachHangjLabel.setForeground(new java.awt.Color(255, 255, 255));
        soDienThoaiKhachHangjLabel.setText("Số điện thoại");

        huyKhachHangjButton.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        huyKhachHangjButton.setForeground(new java.awt.Color(0, 102, 102));
        huyKhachHangjButton.setText("HỦY");
        huyKhachHangjButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                huyKhachHangjButtonActionPerformed(evt);
            }
        });

        nhapKhachHangjButton.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        nhapKhachHangjButton.setForeground(new java.awt.Color(0, 102, 102));
        nhapKhachHangjButton.setText("NHẬP");

        themKhachHangjButton.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        themKhachHangjButton.setForeground(new java.awt.Color(0, 102, 102));
        themKhachHangjButton.setText("THÊM");
        themKhachHangjButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                themKhachHangjButtonActionPerformed(evt);
            }
        });

        xuatKhachHangjButton.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        xuatKhachHangjButton.setForeground(new java.awt.Color(0, 102, 102));
        xuatKhachHangjButton.setText("XUẤT");

        xoaKhachHangjButton.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        xoaKhachHangjButton.setForeground(new java.awt.Color(0, 102, 102));
        xoaKhachHangjButton.setText("XÓA");
        xoaKhachHangjButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                xoaKhachHangjButtonActionPerformed(evt);
            }
        });

        suaKhachHangjButton.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        suaKhachHangjButton.setForeground(new java.awt.Color(0, 102, 102));
        suaKhachHangjButton.setText("SỬA");
        suaKhachHangjButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                suaKhachHangjButtonActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("*");

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("*");

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 0, 0));

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("*");

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("* Các trường có dấu sao là bắt buộc");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane1)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(xuatKhachHangjButton, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(64, 64, 64)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(tenKhachHangjLabel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(maKhachHangjLabel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 151, Short.MAX_VALUE)
                            .addComponent(diaChiKhachHangjLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(35, 35, 35)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(diaChiKhachHangjTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 228, Short.MAX_VALUE)
                            .addComponent(hoTenKhachHangjTextField, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(maKhachHangjTextField, javax.swing.GroupLayout.Alignment.TRAILING)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 189, Short.MAX_VALUE)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(soDienThoaiKhachHangjLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 141, Short.MAX_VALUE)
                            .addComponent(emailKhachHangjLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(31, 31, 31)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(soDienThoaiKhachHangjTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 264, Short.MAX_VALUE)
                            .addComponent(emailKhachHangjTextField))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6))
                        .addGap(107, 107, 107))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(themKhachHangjButton, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(suaKhachHangjButton, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(xoaKhachHangjButton, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(huyKhachHangjButton, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(nhapKhachHangjButton, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(35, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(36, 36, 36)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(emailKhachHangjLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(emailKhachHangjTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(maKhachHangjTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(maKhachHangjLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel5))
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tenKhachHangjLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(soDienThoaiKhachHangjLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(hoTenKhachHangjTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(soDienThoaiKhachHangjTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel6))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(diaChiKhachHangjLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(diaChiKhachHangjTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(16, 16, 16)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(themKhachHangjButton, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(xoaKhachHangjButton, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(suaKhachHangjButton, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(huyKhachHangjButton, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(nhapKhachHangjButton, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addGap(32, 32, 32)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 367, Short.MAX_VALUE)
                .addGap(5, 5, 5)
                .addComponent(xuatKhachHangjButton, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    public void setEnabledButton() {
        huyKhachHangjButton.setEnabled(false);
    }

    private void themKhachHangjButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_themKhachHangjButtonActionPerformed
        // TODO add your handling code here:
        try {
            KhachHang khachHang = new KhachHang();
            String maKhachHang = maKhachHangjTextField.getText();
            if (KhachHangDAO.kiemTraMaKHDaTonTai(maKhachHang)) {
                JOptionPane.showMessageDialog(null, "Mã khách hàng đã tồn tại", "Message", JOptionPane.INFORMATION_MESSAGE, sai);
            } else {
                khachHang.setMaKhachHang(maKhachHang);
                khachHang.setTenKhachHang(tenKhachHangjLabel.getText());
                khachHang.setDiaChiKhachHang(diaChiKhachHangjTextField.getText());
                khachHang.setEmailKhachHang(emailKhachHangjTextField.getText());
                khachHang.setSoDienThoaiKH(soDienThoaiKhachHangjTextField.getText());
                if (KhachHangDAO.themKhachHang(khachHang)) {
                    khachHangtableModel.addRow(new Object[]{
                        khachHang.getMaKhachHang(), khachHang.getTenKhachHang(), khachHang.getDiaChiKhachHang(), khachHang.getSoDienThoaiKH(), khachHang.getEmailKhachHang()
                    });
                    JOptionPane.showMessageDialog(null, "Đã thêm", "Message", JOptionPane.INFORMATION_MESSAGE, dung);

                } else {
                    JOptionPane.showMessageDialog(null, "Kiểm tra lại thông tin nhập vào", "Message", JOptionPane.INFORMATION_MESSAGE, sai);

                }

            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Kiểm tra lại thông tin nhập vào", "Message", JOptionPane.INFORMATION_MESSAGE, sai);

        }

        maKhachHangjTextField.setText("");
        tenKhachHangjLabel.setText("");
        diaChiKhachHangjTextField.setText("");
        emailKhachHangjTextField.setText("");
        soDienThoaiKhachHangjTextField.setText("");
    }//GEN-LAST:event_themKhachHangjButtonActionPerformed

    private void khachHangjTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_khachHangjTableMouseClicked
        // TODO add your handling code here:
        maKhachHangjTextField.setEditable(false);
        int row = khachHangjTable.getSelectedRow();
        maKhachHangjTextField.setText(khachHangtableModel.getValueAt(row, 0).toString());
        hoTenKhachHangjTextField.setText(khachHangtableModel.getValueAt(row, 1).toString());
        diaChiKhachHangjTextField.setText(khachHangtableModel.getValueAt(row, 2).toString());
        soDienThoaiKhachHangjTextField.setText(khachHangtableModel.getValueAt(row, 3).toString());
        emailKhachHangjTextField.setText(khachHangtableModel.getValueAt(row, 4).toString());

        themKhachHangjButton.setEnabled(false);
        nhapKhachHangjButton.setEnabled(false);
        huyKhachHangjButton.setEnabled(true);

    }//GEN-LAST:event_khachHangjTableMouseClicked

    private void suaKhachHangjButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_suaKhachHangjButtonActionPerformed
        // TODO add your handling code here:
        try {
            int row = khachHangjTable.getSelectedRow();
            KhachHang khachHang = new KhachHang();
            String maKhachHang = maKhachHangjTextField.getText();
            khachHang.setMaKhachHang(maKhachHang);
            khachHang.setTenKhachHang(hoTenKhachHangjTextField.getText());
            khachHang.setDiaChiKhachHang(diaChiKhachHangjTextField.getText());
            khachHang.setEmailKhachHang(emailKhachHangjTextField.getText());
            khachHang.setSoDienThoaiKH(soDienThoaiKhachHangjTextField.getText());
            if (KhachHangDAO.suaKhachHang(khachHang, maKhachHang)) {
                khachHangtableModel.setValueAt(khachHang.getTenKhachHang(), row, 1);
                khachHangtableModel.setValueAt(khachHang.getDiaChiKhachHang(), row, 2);
                khachHangtableModel.setValueAt(khachHang.getSoDienThoaiKH(), row, 3);
                khachHangtableModel.setValueAt(khachHang.getEmailKhachHang(), row, 4);

                JOptionPane.showMessageDialog(null, "Đã sửa", "Message", JOptionPane.INFORMATION_MESSAGE, dung);

            } else {
                JOptionPane.showMessageDialog(null, "Kiểm tra lại thông tin nhập vào", "Message", JOptionPane.INFORMATION_MESSAGE, sai);

            }

        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Kiểm tra lại thông tin nhập vào", "Message", JOptionPane.INFORMATION_MESSAGE, sai);

        }

        maKhachHangjTextField.setText("");
        hoTenKhachHangjTextField.setText("");
        diaChiKhachHangjTextField.setText("");
        emailKhachHangjTextField.setText("");
        soDienThoaiKhachHangjTextField.setText("");

        themKhachHangjButton.setEnabled(true);
        nhapKhachHangjButton.setEnabled(true);
        huyKhachHangjButton.setEnabled(false);
    }//GEN-LAST:event_suaKhachHangjButtonActionPerformed

    private void xoaKhachHangjButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_xoaKhachHangjButtonActionPerformed
        // TODO add your handling code here:
        int row = khachHangjTable.getSelectedRow();
        if (row != -1) {
            maKhachHangjTextField.setEditable(false);
            String maKhachHang = maKhachHangjTextField.getText();
            try {
                int luaChon = JOptionPane.showConfirmDialog(null, "Bạn có chắn chắn muốn xóa không", "Message", JOptionPane.YES_NO_OPTION);
                if (luaChon == JOptionPane.YES_OPTION) {
                    if (KhachHangDAO.xoaKhachHang(maKhachHang)) {
                        khachHangtableModel.removeRow(row);
                        JOptionPane.showMessageDialog(null, "Đã xóa", "Message", JOptionPane.INFORMATION_MESSAGE, dung);
                    }
                } else if (luaChon == JOptionPane.NO_OPTION) {

                    JOptionPane.showMessageDialog(null, "Đã hủy việc xóa", "Message", JOptionPane.INFORMATION_MESSAGE, sai);
                }
            } catch (Exception e) {
            }
        } else {
            JOptionPane.showMessageDialog(null, "Chọn một hàng trong bảng để xóa");
        }
        themKhachHangjButton.setEnabled(true);
        nhapKhachHangjButton.setEnabled(true);
        huyKhachHangjButton.setEnabled(false);
    }//GEN-LAST:event_xoaKhachHangjButtonActionPerformed

    private void huyKhachHangjButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_huyKhachHangjButtonActionPerformed
        // TODO add your handling code here:
        maKhachHangjTextField.setText("");
        hoTenKhachHangjTextField.setText("");
        diaChiKhachHangjTextField.setText("");
        emailKhachHangjTextField.setText("");
        soDienThoaiKhachHangjTextField.setText("");
        themKhachHangjButton.setEnabled(true);
        nhapKhachHangjButton.setEnabled(true);
        huyKhachHangjButton.setEnabled(false);
    }//GEN-LAST:event_huyKhachHangjButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel diaChiKhachHangjLabel;
    private javax.swing.JTextField diaChiKhachHangjTextField;
    private javax.swing.JLabel emailKhachHangjLabel;
    private javax.swing.JTextField emailKhachHangjTextField;
    private javax.swing.JTextField hoTenKhachHangjTextField;
    private javax.swing.JButton huyKhachHangjButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable khachHangjTable;
    private javax.swing.JLabel maKhachHangjLabel;
    private javax.swing.JTextField maKhachHangjTextField;
    private javax.swing.JButton nhapKhachHangjButton;
    private javax.swing.JLabel soDienThoaiKhachHangjLabel;
    private javax.swing.JTextField soDienThoaiKhachHangjTextField;
    private javax.swing.JButton suaKhachHangjButton;
    private javax.swing.JLabel tenKhachHangjLabel;
    private javax.swing.JButton themKhachHangjButton;
    private javax.swing.JButton xoaKhachHangjButton;
    private javax.swing.JButton xuatKhachHangjButton;
    // End of variables declaration//GEN-END:variables
}
