/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.qlbh.view;

import com.qlbh.dao.NhaCungCapDAO;
import com.qlbh.model.NhaCungCap;
import com.qlbh.tools.Excel;
import java.io.File;
import java.io.IOException;
import java.util.ArrayList;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import jxl.Cell;
import jxl.Sheet;
import jxl.Workbook;
import jxl.read.biff.BiffException;

/**
 *
 * @author HoangDucTung
 */
public class NhaCungCapJPanel extends javax.swing.JPanel {

    /**
     * Creates new form NhaCungCapJPanel
     */
    DefaultTableModel nhaCungCaptableModel;
    ImageIcon sai = new ImageIcon("tinhsai.png");
    ImageIcon dung = new ImageIcon("dau-check.png");

    public NhaCungCapJPanel(String username) {
        initComponents();
        nhaCungCaptableModel = (DefaultTableModel) nhaCungCapjTable.getModel();
        ArrayList<NhaCungCap> listNhaCungCap = NhaCungCapDAO.getListNhaCungCap();
        for (NhaCungCap nhaCungCap : listNhaCungCap) {
            nhaCungCaptableModel.addRow(new Object[]{
                nhaCungCap.getMaNhaCungCap(), nhaCungCap.getTenNhaCungCap(), nhaCungCap.getDiaChiNhaCungCap(), nhaCungCap.getEmailNhaCungCap(), nhaCungCap.getSoDienThoaiNCC()
            });
        }

        huyNCCjButton.setEnabled(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        nhaCungCapjTable = new javax.swing.JTable();
        maNhaCungCapjLabel = new javax.swing.JLabel();
        tenNhaCungCapjLabel = new javax.swing.JLabel();
        diaChiNhaCungCapjLabel = new javax.swing.JLabel();
        emailNhaCungCapjLabel = new javax.swing.JLabel();
        soDienThoaiNCCjLabel = new javax.swing.JLabel();
        themNCCjButton = new javax.swing.JButton();
        xoaNCCjButton = new javax.swing.JButton();
        nhapNCCjButton = new javax.swing.JButton();
        tenNhaCungCapjTextField = new javax.swing.JTextField();
        diaChiNhaCungCapjTextField = new javax.swing.JTextField();
        maNhaCungCapjTextField = new javax.swing.JTextField();
        soDienThoaiNCCjTextField = new javax.swing.JTextField();
        emailNhaCungCapjTextField = new javax.swing.JTextField();
        huyNCCjButton = new javax.swing.JButton();
        xuatNCCjButton = new javax.swing.JButton();
        suaNCCjButton = new javax.swing.JButton();

        setBackground(new java.awt.Color(0, 102, 102));
        setForeground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Arial", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("NHÀ CUNG CẤP");

        jScrollPane1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Danh sách nhà cung cấp", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 18), new java.awt.Color(0, 102, 102))); // NOI18N

        nhaCungCapjTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Mã nhà cung cấp", "Tên", "Địa chỉ", "Email", "Số điện thoại"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        nhaCungCapjTable.getTableHeader().setReorderingAllowed(false);
        nhaCungCapjTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                nhaCungCapjTableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(nhaCungCapjTable);
        if (nhaCungCapjTable.getColumnModel().getColumnCount() > 0) {
            nhaCungCapjTable.getColumnModel().getColumn(0).setResizable(false);
            nhaCungCapjTable.getColumnModel().getColumn(1).setResizable(false);
            nhaCungCapjTable.getColumnModel().getColumn(2).setResizable(false);
            nhaCungCapjTable.getColumnModel().getColumn(3).setResizable(false);
            nhaCungCapjTable.getColumnModel().getColumn(4).setResizable(false);
        }

        maNhaCungCapjLabel.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        maNhaCungCapjLabel.setForeground(new java.awt.Color(255, 255, 255));
        maNhaCungCapjLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/qlbh/images/business-card-of-folded-diptych-design.png"))); // NOI18N
        maNhaCungCapjLabel.setText("Mã nhà cung cấp");

        tenNhaCungCapjLabel.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        tenNhaCungCapjLabel.setForeground(new java.awt.Color(255, 255, 255));
        tenNhaCungCapjLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/qlbh/images/dog-tag.png"))); // NOI18N
        tenNhaCungCapjLabel.setText("Tên nhà cung cấp");

        diaChiNhaCungCapjLabel.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        diaChiNhaCungCapjLabel.setForeground(new java.awt.Color(255, 255, 255));
        diaChiNhaCungCapjLabel.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        diaChiNhaCungCapjLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/qlbh/images/notebook.png"))); // NOI18N
        diaChiNhaCungCapjLabel.setText("Địa chỉ");

        emailNhaCungCapjLabel.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        emailNhaCungCapjLabel.setForeground(new java.awt.Color(255, 255, 255));
        emailNhaCungCapjLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/qlbh/images/email.png"))); // NOI18N
        emailNhaCungCapjLabel.setText("Email");

        soDienThoaiNCCjLabel.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        soDienThoaiNCCjLabel.setForeground(new java.awt.Color(255, 255, 255));
        soDienThoaiNCCjLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/qlbh/images/agenda.png"))); // NOI18N
        soDienThoaiNCCjLabel.setText("Số điện thoại");

        themNCCjButton.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        themNCCjButton.setForeground(new java.awt.Color(0, 102, 102));
        themNCCjButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/qlbh/images/plus.png"))); // NOI18N
        themNCCjButton.setText("THÊM");
        themNCCjButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                themNCCjButtonActionPerformed(evt);
            }
        });

        xoaNCCjButton.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        xoaNCCjButton.setForeground(new java.awt.Color(0, 102, 102));
        xoaNCCjButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/qlbh/images/database.png"))); // NOI18N
        xoaNCCjButton.setText("XÓA");
        xoaNCCjButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                xoaNCCjButtonActionPerformed(evt);
            }
        });

        nhapNCCjButton.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        nhapNCCjButton.setForeground(new java.awt.Color(0, 102, 102));
        nhapNCCjButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/qlbh/images/import (1).png"))); // NOI18N
        nhapNCCjButton.setText("NHẬP");
        nhapNCCjButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nhapNCCjButtonActionPerformed(evt);
            }
        });

        maNhaCungCapjTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                maNhaCungCapjTextFieldActionPerformed(evt);
            }
        });

        soDienThoaiNCCjTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                soDienThoaiNCCjTextFieldActionPerformed(evt);
            }
        });

        emailNhaCungCapjTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                emailNhaCungCapjTextFieldActionPerformed(evt);
            }
        });

        huyNCCjButton.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        huyNCCjButton.setForeground(new java.awt.Color(0, 102, 102));
        huyNCCjButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/qlbh/images/x-button.png"))); // NOI18N
        huyNCCjButton.setText("HỦY");
        huyNCCjButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                huyNCCjButtonActionPerformed(evt);
            }
        });

        xuatNCCjButton.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        xuatNCCjButton.setForeground(new java.awt.Color(0, 102, 102));
        xuatNCCjButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/qlbh/images/share.png"))); // NOI18N
        xuatNCCjButton.setText("XUẤT");
        xuatNCCjButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                xuatNCCjButtonActionPerformed(evt);
            }
        });

        suaNCCjButton.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        suaNCCjButton.setForeground(new java.awt.Color(0, 102, 102));
        suaNCCjButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/qlbh/images/edit (1).png"))); // NOI18N
        suaNCCjButton.setText("SỬA");
        suaNCCjButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                suaNCCjButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(24, 24, 24)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(tenNhaCungCapjLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(diaChiNhaCungCapjLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(maNhaCungCapjLabel, javax.swing.GroupLayout.Alignment.LEADING))
                                .addGap(142, 142, 142)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(maNhaCungCapjTextField)
                                    .addComponent(tenNhaCungCapjTextField)
                                    .addComponent(diaChiNhaCungCapjTextField))
                                .addGap(93, 93, 93)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(emailNhaCungCapjLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(soDienThoaiNCCjLabel))
                                .addGap(93, 93, 93)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(emailNhaCungCapjTextField)
                                    .addComponent(soDienThoaiNCCjTextField))
                                .addGap(49, 49, 49))
                            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(themNCCjButton, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(suaNCCjButton, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(xoaNCCjButton, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(huyNCCjButton, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(nhapNCCjButton, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(158, 158, 158))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(xuatNCCjButton, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 1290, Short.MAX_VALUE))
                        .addGap(24, 24, 24))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(maNhaCungCapjLabel)
                        .addComponent(maNhaCungCapjTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(emailNhaCungCapjLabel))
                    .addComponent(emailNhaCungCapjTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(soDienThoaiNCCjLabel)
                    .addComponent(tenNhaCungCapjTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(soDienThoaiNCCjTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tenNhaCungCapjLabel))
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(diaChiNhaCungCapjLabel)
                    .addComponent(diaChiNhaCungCapjTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nhapNCCjButton, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(huyNCCjButton, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(xoaNCCjButton, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(themNCCjButton, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(suaNCCjButton, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(38, 38, 38)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 394, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(xuatNCCjButton, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(13, 13, 13))
        );
    }// </editor-fold>//GEN-END:initComponents


    private void maNhaCungCapjTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_maNhaCungCapjTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_maNhaCungCapjTextFieldActionPerformed

    private void soDienThoaiNCCjTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_soDienThoaiNCCjTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_soDienThoaiNCCjTextFieldActionPerformed

    private void emailNhaCungCapjTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_emailNhaCungCapjTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_emailNhaCungCapjTextFieldActionPerformed

    private void themNCCjButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_themNCCjButtonActionPerformed
        // TODO add your handling code here:
        try {
            NhaCungCap nhaCungCap = new NhaCungCap();
            String maNhaCungCap = maNhaCungCapjTextField.getText().toUpperCase();
            if (NhaCungCapDAO.kiemTraMaNhaCungCapDaTonTai(maNhaCungCap)) {
                JOptionPane.showMessageDialog(null, "Mã nhà cung cấp đã tồn tại", "Message", JOptionPane.INFORMATION_MESSAGE, sai);
            } else {
                nhaCungCap.setMaNhaCungCap(maNhaCungCap);
                nhaCungCap.setTenNhaCungCap(tenNhaCungCapjTextField.getText());
                nhaCungCap.setDiaChiNhaCungCap(diaChiNhaCungCapjTextField.getText());
                nhaCungCap.setEmailNhaCungCap(emailNhaCungCapjTextField.getText());
                nhaCungCap.setSoDienThoaiNCC(soDienThoaiNCCjTextField.getText());
                if (NhaCungCapDAO.themNhaCungCap(nhaCungCap)) {
                    nhaCungCaptableModel.addRow(new Object[]{
                        nhaCungCap.getMaNhaCungCap(), nhaCungCap.getTenNhaCungCap(), nhaCungCap.getDiaChiNhaCungCap(), nhaCungCap.getEmailNhaCungCap(), nhaCungCap.getSoDienThoaiNCC()
                    });
                    JOptionPane.showMessageDialog(null, "Đã thêm", "Message", JOptionPane.INFORMATION_MESSAGE, dung);

                } else {
                    JOptionPane.showMessageDialog(null, "Kiểm tra lại thông tin nhập vào", "Message", JOptionPane.INFORMATION_MESSAGE, sai);

                }

            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Kiểm tra lại thông tin nhập vào", "Message", JOptionPane.INFORMATION_MESSAGE, sai);
        }
        setDefaultInput();
    }//GEN-LAST:event_themNCCjButtonActionPerformed

    private void nhaCungCapjTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_nhaCungCapjTableMouseClicked
        // TODO add your handling code here:
        themNCCjButton.setEnabled(false);
        nhapNCCjButton.setEnabled(false);
        huyNCCjButton.setEnabled(true);
        int row = nhaCungCapjTable.getSelectedRow();
        maNhaCungCapjTextField.setText(nhaCungCaptableModel.getValueAt(row, 0).toString());
        tenNhaCungCapjTextField.setText(nhaCungCaptableModel.getValueAt(row, 1).toString());
        diaChiNhaCungCapjTextField.setText(nhaCungCaptableModel.getValueAt(row, 2).toString());
        emailNhaCungCapjTextField.setText(nhaCungCaptableModel.getValueAt(row, 3).toString());
        soDienThoaiNCCjTextField.setText(nhaCungCaptableModel.getValueAt(row, 4).toString());


    }//GEN-LAST:event_nhaCungCapjTableMouseClicked

    private void suaNCCjButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_suaNCCjButtonActionPerformed
        // TODO add your handling code here:
        int row = nhaCungCapjTable.getSelectedRow();
        if (row != -1) {
            maNhaCungCapjTextField.setEditable(false);
            String maNhaCungCap = maNhaCungCapjTextField.getText().toUpperCase();
            NhaCungCap nhaCungCap = new NhaCungCap();
            try {
                nhaCungCap.setMaNhaCungCap(maNhaCungCap);
                nhaCungCap.setTenNhaCungCap(tenNhaCungCapjTextField.getText());
                nhaCungCap.setDiaChiNhaCungCap(diaChiNhaCungCapjTextField.getText());
                nhaCungCap.setEmailNhaCungCap(emailNhaCungCapjTextField.getText());
                nhaCungCap.setSoDienThoaiNCC(soDienThoaiNCCjTextField.getText());
                if (NhaCungCapDAO.suaNhaCungCap(nhaCungCap, maNhaCungCap)) {
                    nhaCungCaptableModel.setValueAt(nhaCungCap.getTenNhaCungCap(), row, 1);
                    nhaCungCaptableModel.setValueAt(nhaCungCap.getDiaChiNhaCungCap(), row, 2);
                    nhaCungCaptableModel.setValueAt(nhaCungCap.getEmailNhaCungCap(), row, 3);
                    nhaCungCaptableModel.setValueAt(nhaCungCap.getSoDienThoaiNCC(), row, 4);
                    JOptionPane.showMessageDialog(null, "Đã sửa", "Message", JOptionPane.INFORMATION_MESSAGE, dung);

                } else {
                    JOptionPane.showMessageDialog(null, "Kiểm tra thông tin nhập vào", "Message", JOptionPane.INFORMATION_MESSAGE, sai);

                }
            } catch (Exception e) {
            }
        } else {
            JOptionPane.showMessageDialog(null, "Chọn một hàng để sửa", "Message", JOptionPane.INFORMATION_MESSAGE, sai);
        }
        setDefaultInput();
        huyNCCjButton.setEnabled(false);
        themNCCjButton.setEnabled(true);
        nhapNCCjButton.setEnabled(true);
    }//GEN-LAST:event_suaNCCjButtonActionPerformed

    private void xoaNCCjButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_xoaNCCjButtonActionPerformed
        // TODO add your handling code here:
        int row = nhaCungCapjTable.getSelectedRow();
        if (row != -1) {
            maNhaCungCapjTextField.setEditable(false);
            String maNhaCungCap = maNhaCungCapjTextField.getText();
            try {
                int luaChon = JOptionPane.showConfirmDialog(null, "Bạn có chắn chắn muốn xóa không", "Message", JOptionPane.YES_NO_OPTION);
                if (luaChon == JOptionPane.YES_OPTION) {
                    if (NhaCungCapDAO.xoaNhaCungCap(maNhaCungCap)) {
                        nhaCungCaptableModel.removeRow(row);
                        JOptionPane.showMessageDialog(null, "Đã xóa", "Message", JOptionPane.INFORMATION_MESSAGE, dung);
                    }
                } else if (luaChon == JOptionPane.NO_OPTION) {

                    JOptionPane.showMessageDialog(null, "Đã hủy việc xóa", "Message", JOptionPane.INFORMATION_MESSAGE, sai);
                }
            } catch (Exception e) {
            }
        } else {
            JOptionPane.showMessageDialog(null, "Chọn một hàng để xóa", "Message", JOptionPane.INFORMATION_MESSAGE, sai);
        }
        setDefaultInput();
        huyNCCjButton.setEnabled(false);
        themNCCjButton.setEnabled(true);
        nhapNCCjButton.setEnabled(true);
    }//GEN-LAST:event_xoaNCCjButtonActionPerformed

    private void huyNCCjButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_huyNCCjButtonActionPerformed
        // TODO add your handling code here:
        themNCCjButton.setEnabled(true);
        nhapNCCjButton.setEnabled(true);
        huyNCCjButton.setEnabled(false);
        maNhaCungCapjTextField.setText("");
        tenNhaCungCapjTextField.setText("");
        diaChiNhaCungCapjTextField.setText("");
        emailNhaCungCapjTextField.setText("");
        soDienThoaiNCCjTextField.setText("");
        nhaCungCapjTable.clearSelection();
    }//GEN-LAST:event_huyNCCjButtonActionPerformed

    private void xuatNCCjButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_xuatNCCjButtonActionPerformed
        // TODO add your handling code here:
        JFileChooser chooser = new JFileChooser();
        chooser.setCurrentDirectory(new java.io.File("."));
        chooser.setDialogTitle("Chọn thư mục để lưu");
        chooser.setFileSelectionMode(JFileChooser.DIRECTORIES_ONLY);
        chooser.setAcceptAllFileFilterUsed(false);
        if (chooser.showOpenDialog(null) == JFileChooser.APPROVE_OPTION) {
            Excel.xuatFileExcel(nhaCungCapjTable, chooser.getSelectedFile() + "\\\\Nhacungcap.xls");
            JOptionPane.showMessageDialog(null, "Đã lưu file tại đường dẫn: " + chooser.getSelectedFile(), "Message", JOptionPane.INFORMATION_MESSAGE, dung);
        } else {
        }
    }//GEN-LAST:event_xuatNCCjButtonActionPerformed

    private void nhapNCCjButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nhapNCCjButtonActionPerformed
        // TODO add your handling code here:
        JFileChooser jFileChooser = new JFileChooser();
        jFileChooser.setDialogTitle("Chọn file");
        int chonFile = jFileChooser.showOpenDialog(null);
        if (chonFile == JFileChooser.APPROVE_OPTION) {
            try {
                int count = 0;
                String duongDanExcel = jFileChooser.getSelectedFile().getAbsolutePath();
                JOptionPane.showMessageDialog(null, duongDanExcel);
                File file = new File(duongDanExcel);
                Workbook workbook = Workbook.getWorkbook(file);
                Sheet sheet = workbook.getSheet(0);
                int row = sheet.getRows();
                for (int i = 1; i < row; i++) {
                    Cell col1 = sheet.getCell(0, i);
                    Cell col2 = sheet.getCell(1, i);
                    Cell col3 = sheet.getCell(2, i);
                    Cell col4 = sheet.getCell(3, i);
                    Cell col5 = sheet.getCell(4, i);
                    String maNCC = col1.getContents();
                    String tenNCC = col2.getContents();
                    String diaChiNCC = col3.getContents();
                    String emailNCC = col4.getContents();
                    String soDienThoaiNCC = col5.getContents();
                    NhaCungCap nhaCungCap = new NhaCungCap(maNCC, tenNCC, diaChiNCC, emailNCC, soDienThoaiNCC);
                    if (NhaCungCapDAO.themNhaCungCap(nhaCungCap)) {
                        nhaCungCaptableModel.addRow(new Object[]{
                            nhaCungCap.getMaNhaCungCap(),
                            nhaCungCap.getTenNhaCungCap(),
                            nhaCungCap.getDiaChiNhaCungCap(),
                            nhaCungCap.getEmailNhaCungCap(),
                            nhaCungCap.getSoDienThoaiNCC()
                        });
                        count++;
                    } else {
                        JOptionPane.showMessageDialog(null, "Kiểm tra lại giá trị trong file", "Message", JOptionPane.INFORMATION_MESSAGE, sai);
                    }

                }
                if (count == row - 1) {
                    JOptionPane.showMessageDialog(null, "Nhập file thành công", "Message", JOptionPane.INFORMATION_MESSAGE, dung);

                }
            } catch (IOException ex) {
                JOptionPane.showMessageDialog(null, "Kiểm tra lại cấu trúc file", "Message", JOptionPane.INFORMATION_MESSAGE, sai);
            } catch (BiffException ex) {
                JOptionPane.showMessageDialog(null, "Kiểm tra lại cấu trúc file", "Message", JOptionPane.INFORMATION_MESSAGE, sai);
            }
        }
    }//GEN-LAST:event_nhapNCCjButtonActionPerformed

    public void setDefaultInput() {
        tenNhaCungCapjTextField.setText("");
        maNhaCungCapjTextField.setText("");
        diaChiNhaCungCapjTextField.setText("");
        emailNhaCungCapjTextField.setText("");
        soDienThoaiNCCjTextField.setText("");
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel diaChiNhaCungCapjLabel;
    private javax.swing.JTextField diaChiNhaCungCapjTextField;
    private javax.swing.JLabel emailNhaCungCapjLabel;
    private javax.swing.JTextField emailNhaCungCapjTextField;
    private javax.swing.JButton huyNCCjButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel maNhaCungCapjLabel;
    private javax.swing.JTextField maNhaCungCapjTextField;
    private javax.swing.JTable nhaCungCapjTable;
    private javax.swing.JButton nhapNCCjButton;
    private javax.swing.JLabel soDienThoaiNCCjLabel;
    private javax.swing.JTextField soDienThoaiNCCjTextField;
    private javax.swing.JButton suaNCCjButton;
    private javax.swing.JLabel tenNhaCungCapjLabel;
    private javax.swing.JTextField tenNhaCungCapjTextField;
    private javax.swing.JButton themNCCjButton;
    private javax.swing.JButton xoaNCCjButton;
    private javax.swing.JButton xuatNCCjButton;
    // End of variables declaration//GEN-END:variables
}
