/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.qlbh.view;

import com.qlbh.dao.NhanVienDAO;
import com.qlbh.model.NhanVien;
import com.qlbh.tools.DatesConversion;
import java.util.ArrayList;
import java.util.Date;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author HoangDucTung
 */
public class NhanVienJFrame extends javax.swing.JFrame {

    /**
     * Creates new form NhanVienJFrame
     */
    DefaultTableModel nhanVienTableModel;
    ImageIcon sai = new ImageIcon("tinhsai.png");
    ImageIcon dung = new ImageIcon("dau-check.png");
    
    public NhanVienJFrame() {
        initComponents();
        nhanVienTableModel = (DefaultTableModel) nhanVienjTable.getModel();
        loadNhanVien();
        huyNhanVienjButton.setEnabled(false);
        NhanVienJFrame.super.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        nhanVienjTable = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        maNhanVienjTextField = new javax.swing.JTextField();
        diaChijTextField = new javax.swing.JTextField();
        hoTenjTextField = new javax.swing.JTextField();
        namjRadioButton = new javax.swing.JRadioButton();
        nujRadioButton = new javax.swing.JRadioButton();
        ngaySinhjDateChooser = new com.toedter.calendar.JDateChooser();
        soDienThoaijTextField = new javax.swing.JTextField();
        emailjTextField = new javax.swing.JTextField();
        chucVujTextField = new javax.swing.JTextField();
        luongjTextField = new javax.swing.JTextField();
        suaNhanVienjButton = new javax.swing.JButton();
        xoaNhanVienjButton = new javax.swing.JButton();
        huyNhanVienjButton = new javax.swing.JButton();
        nhapNhanVienjButton = new javax.swing.JButton();
        xuatNhanVienjButton = new javax.swing.JButton();
        themNhanVienjButton = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(253, 255, 252));

        jLabel1.setBackground(new java.awt.Color(231, 29, 54));
        jLabel1.setFont(new java.awt.Font("Arial", 1, 20)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(253, 255, 252));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("QUẢN LÍ NHÂN VIÊN");
        jLabel1.setOpaque(true);

        nhanVienjTable.setBackground(new java.awt.Color(255, 253, 252));
        nhanVienjTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Mã nhân viên", "Họ tên", "Giới tính", "Ngày sinh", "Số điện thoại", "Email", "Địa chỉ", "Chức vụ", "Lương"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        nhanVienjTable.setFocusable(false);
        nhanVienjTable.setGridColor(new java.awt.Color(255, 252, 253));
        nhanVienjTable.getTableHeader().setReorderingAllowed(false);
        nhanVienjTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                nhanVienjTableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(nhanVienjTable);
        if (nhanVienjTable.getColumnModel().getColumnCount() > 0) {
            nhanVienjTable.getColumnModel().getColumn(0).setResizable(false);
            nhanVienjTable.getColumnModel().getColumn(1).setResizable(false);
            nhanVienjTable.getColumnModel().getColumn(2).setResizable(false);
            nhanVienjTable.getColumnModel().getColumn(3).setResizable(false);
            nhanVienjTable.getColumnModel().getColumn(4).setResizable(false);
            nhanVienjTable.getColumnModel().getColumn(5).setResizable(false);
            nhanVienjTable.getColumnModel().getColumn(6).setResizable(false);
            nhanVienjTable.getColumnModel().getColumn(7).setResizable(false);
            nhanVienjTable.getColumnModel().getColumn(8).setResizable(false);
        }

        jPanel2.setBackground(new java.awt.Color(253, 255, 252));
        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Thông tin nhân viên", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Arial", 1, 18), new java.awt.Color(231, 29, 54))); // NOI18N

        jLabel2.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel2.setText("Mã nhân viên");

        jLabel3.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel3.setText("Họ tên");

        jLabel4.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel4.setText("Giới tính");

        jLabel5.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel5.setText("Ngày sinh");

        jLabel6.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel6.setText("Số điện thoại");

        jLabel7.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel7.setText("Email");

        jLabel8.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel8.setText("Địa chỉ");

        jLabel9.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel9.setText("Chức vụ");

        jLabel10.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel10.setText("Lương");

        maNhanVienjTextField.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        diaChijTextField.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        hoTenjTextField.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        buttonGroup1.add(namjRadioButton);
        namjRadioButton.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        namjRadioButton.setText("Nam");

        buttonGroup1.add(nujRadioButton);
        nujRadioButton.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        nujRadioButton.setText("Nữ");

        ngaySinhjDateChooser.setDateFormatString("dd/MM/yyyy");
        ngaySinhjDateChooser.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        soDienThoaijTextField.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        emailjTextField.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        chucVujTextField.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        luongjTextField.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        suaNhanVienjButton.setBackground(new java.awt.Color(1, 22, 39));
        suaNhanVienjButton.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        suaNhanVienjButton.setForeground(new java.awt.Color(253, 255, 252));
        suaNhanVienjButton.setText("SỬA");
        suaNhanVienjButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                suaNhanVienjButtonActionPerformed(evt);
            }
        });

        xoaNhanVienjButton.setBackground(new java.awt.Color(1, 22, 39));
        xoaNhanVienjButton.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        xoaNhanVienjButton.setForeground(new java.awt.Color(253, 255, 252));
        xoaNhanVienjButton.setText("XÓA");
        xoaNhanVienjButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                xoaNhanVienjButtonActionPerformed(evt);
            }
        });

        huyNhanVienjButton.setBackground(new java.awt.Color(1, 22, 39));
        huyNhanVienjButton.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        huyNhanVienjButton.setForeground(new java.awt.Color(253, 255, 252));
        huyNhanVienjButton.setText("HỦY");
        huyNhanVienjButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                huyNhanVienjButtonActionPerformed(evt);
            }
        });

        nhapNhanVienjButton.setBackground(new java.awt.Color(1, 22, 39));
        nhapNhanVienjButton.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        nhapNhanVienjButton.setForeground(new java.awt.Color(253, 255, 252));
        nhapNhanVienjButton.setText("NHẬP");

        xuatNhanVienjButton.setBackground(new java.awt.Color(1, 22, 39));
        xuatNhanVienjButton.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        xuatNhanVienjButton.setForeground(new java.awt.Color(253, 255, 252));
        xuatNhanVienjButton.setText("XUẤT");

        themNhanVienjButton.setBackground(new java.awt.Color(1, 22, 39));
        themNhanVienjButton.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        themNhanVienjButton.setForeground(new java.awt.Color(253, 255, 252));
        themNhanVienjButton.setText("THÊM");
        themNhanVienjButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                themNhanVienjButtonActionPerformed(evt);
            }
        });

        jLabel11.setForeground(new java.awt.Color(255, 0, 0));
        jLabel11.setText("*");

        jLabel12.setForeground(new java.awt.Color(255, 0, 0));
        jLabel12.setText("*");

        jLabel13.setForeground(new java.awt.Color(255, 0, 0));
        jLabel13.setText("*");

        jLabel14.setForeground(new java.awt.Color(255, 0, 0));
        jLabel14.setText("*");

        jLabel16.setForeground(new java.awt.Color(255, 0, 0));
        jLabel16.setText("*");

        jLabel17.setForeground(new java.awt.Color(255, 0, 0));
        jLabel17.setText("*");

        jLabel15.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 0, 0));
        jLabel15.setText("* Các trường có dấu sao là bắt buộc");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(38, 38, 38)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(20, 20, 20)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(diaChijTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(maNhanVienjTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLabel11))
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(ngaySinhjDateChooser, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLabel12)))
                                .addGap(97, 97, 97))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(themNhanVienjButton, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(60, 60, 60)
                                .addComponent(suaNhanVienjButton, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(60, 60, 60)))
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(20, 20, 20)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addGroup(jPanel2Layout.createSequentialGroup()
                                            .addComponent(hoTenjTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(jLabel13)
                                            .addGap(56, 56, 56)
                                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(jPanel2Layout.createSequentialGroup()
                                            .addComponent(soDienThoaijTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(chucVujTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLabel17)
                                        .addGap(56, 56, 56)
                                        .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(20, 20, 20)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(emailjTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addGroup(jPanel2Layout.createSequentialGroup()
                                            .addGap(11, 11, 11)
                                            .addComponent(namjRadioButton)
                                            .addGap(18, 18, 18)
                                            .addComponent(nujRadioButton)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(jLabel14))
                                        .addGroup(jPanel2Layout.createSequentialGroup()
                                            .addComponent(luongjTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(jLabel16)))))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(xoaNhanVienjButton, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(60, 60, 60)
                                .addComponent(huyNhanVienjButton, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(60, 60, 60)
                                .addComponent(nhapNhanVienjButton, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(60, 60, 60)
                                .addComponent(xuatNhanVienjButton, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel15)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(maNhanVienjTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(hoTenjTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(namjRadioButton)
                    .addComponent(nujRadioButton)
                    .addComponent(jLabel11)
                    .addComponent(jLabel13)
                    .addComponent(jLabel14))
                .addGap(43, 43, 43)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(soDienThoaijTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(emailjTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel12))
                    .addComponent(ngaySinhjDateChooser, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(43, 43, 43)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(diaChijTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(chucVujTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(luongjTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel16)
                    .addComponent(jLabel17))
                .addGap(26, 26, 26)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(suaNhanVienjButton, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(xoaNhanVienjButton, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(huyNhanVienjButton, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(nhapNhanVienjButton, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(xuatNhanVienjButton, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(themNhanVienjButton, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 15, Short.MAX_VALUE)
                .addComponent(jLabel15))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(520, 520, 520)
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 1270, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 338, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        jMenu1.setMnemonic('s');
        jMenu1.setText("Quản lí tài khoản");
        jMenu1.setToolTipText("");
        jMenu1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenu1MouseClicked(evt);
            }
        });
        jMenuBar1.add(jMenu1);

        jMenu2.setText("Thoát");
        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public void loadNhanVien() {
        ArrayList<NhanVien> listNhanVien = NhanVienDAO.getListNhanVien();
        for (NhanVien nhanVien : listNhanVien) {
            nhanVienTableModel.addRow(new Object[]{
                nhanVien.getMaNhanVien(), nhanVien.getTenNhanVien(), nhanVien.isGioiTinh() == true ? "Nam" : "Nữ", nhanVien.getNgaySinh(), nhanVien.getSoDienThoai(), nhanVien.getEmailNhanVien(), nhanVien.getDiaChiNhanVien(), nhanVien.getChucVu(), nhanVien.getLuongNhanVien()
            });
        }
    }

    private void jMenu1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu1MouseClicked
        // TODO add your handling code here:
        AccountManager accountManager = new AccountManager("administrator");
        accountManager.setLocationRelativeTo(null);
        accountManager.setResizable(false);
        accountManager.setVisible(true);
        this.dispose();

    }//GEN-LAST:event_jMenu1MouseClicked

    private void nhanVienjTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_nhanVienjTableMouseClicked
        // TODO add your handling code here:
        themNhanVienjButton.setEnabled(false);
        huyNhanVienjButton.setEnabled(true);
        nhapNhanVienjButton.setEnabled(false);
        xuatNhanVienjButton.setEnabled(false);
        int row = nhanVienjTable.getSelectedRow();
        maNhanVienjTextField.setText(nhanVienTableModel.getValueAt(row, 0).toString());
        maNhanVienjTextField.setEditable(false);
        hoTenjTextField.setText(nhanVienTableModel.getValueAt(row, 1).toString());
        ngaySinhjDateChooser.setDate((Date) nhanVienTableModel.getValueAt(row, 3));
        if (nhanVienTableModel.getValueAt(row, 2).toString().equals("Nam")) {
            namjRadioButton.setSelected(true);
        } else {
            nujRadioButton.setSelected(true);
        }
        if (nhanVienTableModel.getValueAt(row, 4) != null) {
            soDienThoaijTextField.setText(nhanVienTableModel.getValueAt(row, 4).toString());
        } else {
            soDienThoaijTextField.setText("");
        }
        if (nhanVienTableModel.getValueAt(row, 5) != null) {
            emailjTextField.setText(nhanVienTableModel.getValueAt(row, 5).toString());
        } else {
            emailjTextField.setText("");
        }
        if (nhanVienTableModel.getValueAt(row, 6) != null) {
            diaChijTextField.setText(nhanVienTableModel.getValueAt(row, 6).toString());
        } else {
            diaChijTextField.setText("");
        }
        if (nhanVienTableModel.getValueAt(row, 7) != null) {
            chucVujTextField.setText(nhanVienTableModel.getValueAt(row, 7).toString());
        } else {
            chucVujTextField.setText("");
        }
        if (nhanVienTableModel.getValueAt(row, 8) != null) {
            luongjTextField.setText(nhanVienTableModel.getValueAt(row, 8).toString());
        } else {
            luongjTextField.setText("");
        }
    }//GEN-LAST:event_nhanVienjTableMouseClicked

    private void themNhanVienjButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_themNhanVienjButtonActionPerformed
        // TODO add your handling code here:
        try {
            String maNhanVien = maNhanVienjTextField.getText().toUpperCase();
            if (NhanVienDAO.kiemTraMaNhanVienDaTonTai(maNhanVien)) {
                JOptionPane.showMessageDialog(null, "Mã nhân viên đã tồn tại", "Message", JOptionPane.INFORMATION_MESSAGE, sai);
                
            } else {
                NhanVien nhanVien = new NhanVien();
                nhanVien.setMaNhanVien(maNhanVien);
                nhanVien.setTenNhanVien(hoTenjTextField.getText());
                nhanVien.setGioiTinh(namjRadioButton.isSelected() ? true : false);
                nhanVien.setNgaySinh( DatesConversion.convertUtilToSql(ngaySinhjDateChooser.getDate()));
                if (soDienThoaijTextField.getText() != null) {
                    nhanVien.setSoDienThoai(soDienThoaijTextField.getText());
                } else {
                    nhanVien.setSoDienThoai("");
                }
                if (emailjTextField.getText() != null) {
                    nhanVien.setEmailNhanVien(emailjTextField.getText());
                } else {
                    nhanVien.setEmailNhanVien("");
                }
                if (diaChijTextField.getText() != null) {
                    nhanVien.setDiaChiNhanVien(diaChijTextField.getText());
                } else {
                    nhanVien.setDiaChiNhanVien("");
                }
                nhanVien.setChucVu(chucVujTextField.getText());
                nhanVien.setLuongNhanVien(Double.parseDouble(luongjTextField.getText()));
                if (NhanVienDAO.themNhanVien(nhanVien)) {
                    nhanVienTableModel.addRow(new Object[]{
                        nhanVien.getMaNhanVien(), nhanVien.getTenNhanVien(), nhanVien.isGioiTinh() == true ? "Nam" : "Nữ", nhanVien.getNgaySinh(), nhanVien.getSoDienThoai(), nhanVien.getEmailNhanVien(), nhanVien.getDiaChiNhanVien(), nhanVien.getChucVu(), nhanVien.getLuongNhanVien()
                    });
                    JOptionPane.showMessageDialog(null, "Đã thêm nhân viên!", "Message", JOptionPane.INFORMATION_MESSAGE, dung);
                } else {
                    JOptionPane.showMessageDialog(null, "Có lỗi xảy ra, thử lại sau!", "Message", JOptionPane.INFORMATION_MESSAGE, sai);
                    
                }
                
            }
        } catch (Exception e) {
            e.printStackTrace();
           // JOptionPane.showMessageDialog(null, "Kiểm tra giá trị nhập vào", "Message", JOptionPane.INFORMATION_MESSAGE, sai);
        }
        
        maNhanVienjTextField.setText("");
        hoTenjTextField.setText("");
        ngaySinhjDateChooser.setCalendar(null);
        namjRadioButton.setSelected(false);
        nujRadioButton.setSelected(false);
        soDienThoaijTextField.setText("");
        emailjTextField.setText("");
        diaChijTextField.setText("");
        chucVujTextField.setText("");
        luongjTextField.setText("");

    }//GEN-LAST:event_themNhanVienjButtonActionPerformed

    private void suaNhanVienjButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_suaNhanVienjButtonActionPerformed
        // TODO add your handling code here:
        try {
            int row = nhanVienjTable.getSelectedRow();
            if (row != -1) {
                String maNhanVien = maNhanVienjTextField.getText().toUpperCase();
                NhanVien nhanVien = new NhanVien();
                nhanVien.setTenNhanVien(hoTenjTextField.getText());
                nhanVien.setGioiTinh(namjRadioButton.isSelected() ? true : false);
                nhanVien.setNgaySinh( DatesConversion.convertUtilToSql(ngaySinhjDateChooser.getDate()));
                if (soDienThoaijTextField.getText() != null) {
                    nhanVien.setSoDienThoai(soDienThoaijTextField.getText());
                } else {
                    nhanVien.setSoDienThoai("");
                }
                if (emailjTextField.getText() != null) {
                    nhanVien.setEmailNhanVien(emailjTextField.getText());
                } else {
                    nhanVien.setEmailNhanVien("");
                }
                if (diaChijTextField.getText() != null) {
                    nhanVien.setDiaChiNhanVien(diaChijTextField.getText());
                } else {
                    nhanVien.setDiaChiNhanVien("");
                }
                nhanVien.setChucVu(chucVujTextField.getText());
                nhanVien.setLuongNhanVien(Double.parseDouble(luongjTextField.getText()));
                if (NhanVienDAO.suaNhanVien(nhanVien, maNhanVien)) {
                    nhanVienTableModel.setValueAt(nhanVien.getTenNhanVien(), row, 1);
                    nhanVienTableModel.setValueAt(nhanVien.isGioiTinh() == true ? "Nam" : "Nữ", row, 2);
                    nhanVienTableModel.setValueAt(nhanVien.getNgaySinh(), row, 3);
                    nhanVienTableModel.setValueAt(nhanVien.getSoDienThoai(), row, 4);
                    nhanVienTableModel.setValueAt(nhanVien.getEmailNhanVien(), row, 5);
                    nhanVienTableModel.setValueAt(nhanVien.getDiaChiNhanVien(), row, 6);
                    nhanVienTableModel.setValueAt(nhanVien.getChucVu(), row, 7);
                    nhanVienTableModel.setValueAt(nhanVien.getLuongNhanVien(), row, 8);
                    JOptionPane.showMessageDialog(null, "Đã chỉnh sửa nhân viên!", "Message", JOptionPane.INFORMATION_MESSAGE, dung);
                } else {
                    JOptionPane.showMessageDialog(null, "Có lỗi xảy ra, thử lại sau!", "Message", JOptionPane.INFORMATION_MESSAGE, sai);
                    
                }
            } else {
                JOptionPane.showMessageDialog(null, "Chọn một hàng để sửa!", "Message", JOptionPane.INFORMATION_MESSAGE, sai);
                
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Kiểm tra lại thông tin nhập vào!", "Message", JOptionPane.INFORMATION_MESSAGE, sai);
            
        }
        maNhanVienjTextField.setText("");
        maNhanVienjTextField.setEditable(true);
        hoTenjTextField.setText("");
        ngaySinhjDateChooser.setCalendar(null);
        namjRadioButton.setSelected(false);
        nujRadioButton.setSelected(false);
        soDienThoaijTextField.setText("");
        emailjTextField.setText("");
        diaChijTextField.setText("");
        chucVujTextField.setText("");
        luongjTextField.setText("");
        
        themNhanVienjButton.setEnabled(true);
        nhapNhanVienjButton.setEnabled(true);
        huyNhanVienjButton.setEnabled(false);
        xuatNhanVienjButton.setEnabled(true);

    }//GEN-LAST:event_suaNhanVienjButtonActionPerformed

    private void xoaNhanVienjButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_xoaNhanVienjButtonActionPerformed
        // TODO add your handling code here:
        try {
            int row = nhanVienjTable.getSelectedRow();
            if (row != -1) {
                String maNhanVien = maNhanVienjTextField.getText();
                int luachon = JOptionPane.showConfirmDialog(null, "Bạn có chắc chắn muôn xóa không?", "Message", JOptionPane.YES_NO_OPTION);
                if (luachon == JOptionPane.YES_OPTION) {
                    if (NhanVienDAO.xoaNhanVien(maNhanVien)) {
                        nhanVienTableModel.removeRow(row);
                        JOptionPane.showMessageDialog(null, "Đã xóa!", "Message", JOptionPane.INFORMATION_MESSAGE, dung);
                        
                    } else {
                        JOptionPane.showMessageDialog(null, "Có lỗi xảy ra, thử lại sau!", "Message", JOptionPane.INFORMATION_MESSAGE, sai);
                        
                    }
                    
                } else if (luachon == JOptionPane.NO_OPTION) {
                    JOptionPane.showMessageDialog(null, "Đã hủy việc xóa!", "Message", JOptionPane.INFORMATION_MESSAGE, dung);
                    
                }
                
            } else {
                JOptionPane.showMessageDialog(null, "Chọn một hàng để xóa!", "Message", JOptionPane.INFORMATION_MESSAGE, sai);
                
            }
            
        } catch (Exception e) {
        }
        
        maNhanVienjTextField.setText("");
        hoTenjTextField.setText("");
        ngaySinhjDateChooser.setCalendar(null);
        namjRadioButton.setSelected(false);
        nujRadioButton.setSelected(false);
        soDienThoaijTextField.setText("");
        emailjTextField.setText("");
        diaChijTextField.setText("");
        chucVujTextField.setText("");
        luongjTextField.setText("");
        
        themNhanVienjButton.setEnabled(true);
        nhapNhanVienjButton.setEnabled(true);
        huyNhanVienjButton.setEnabled(false);
        xuatNhanVienjButton.setEnabled(true);
    }//GEN-LAST:event_xoaNhanVienjButtonActionPerformed

    private void huyNhanVienjButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_huyNhanVienjButtonActionPerformed
        // TODO add your handling code here:
        maNhanVienjTextField.setText("");
        maNhanVienjTextField.setEditable(true);
        hoTenjTextField.setText("");
        ngaySinhjDateChooser.setCalendar(null);
        namjRadioButton.setSelected(false);
        nujRadioButton.setSelected(false);
        soDienThoaijTextField.setText("");
        emailjTextField.setText("");
        diaChijTextField.setText("");
        chucVujTextField.setText("");
        luongjTextField.setText("");
        themNhanVienjButton.setEnabled(true);
        nhapNhanVienjButton.setEnabled(true);
        huyNhanVienjButton.setEnabled(false);
        xuatNhanVienjButton.setEnabled(true);
        nhanVienjTable.clearSelection();
    }//GEN-LAST:event_huyNhanVienjButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NhanVienJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NhanVienJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NhanVienJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NhanVienJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NhanVienJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JTextField chucVujTextField;
    private javax.swing.JTextField diaChijTextField;
    private javax.swing.JTextField emailjTextField;
    private javax.swing.JTextField hoTenjTextField;
    private javax.swing.JButton huyNhanVienjButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField luongjTextField;
    private javax.swing.JTextField maNhanVienjTextField;
    private javax.swing.JRadioButton namjRadioButton;
    private com.toedter.calendar.JDateChooser ngaySinhjDateChooser;
    private javax.swing.JTable nhanVienjTable;
    private javax.swing.JButton nhapNhanVienjButton;
    private javax.swing.JRadioButton nujRadioButton;
    private javax.swing.JTextField soDienThoaijTextField;
    private javax.swing.JButton suaNhanVienjButton;
    private javax.swing.JButton themNhanVienjButton;
    private javax.swing.JButton xoaNhanVienjButton;
    private javax.swing.JButton xuatNhanVienjButton;
    // End of variables declaration//GEN-END:variables
}
