/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.qlbh.view;

import com.qlbh.dao.KhachHangDAO;
import com.qlbh.dao.NhaCungCapDAO;
import com.qlbh.dao.SanPhamDAO;
import com.qlbh.model.KhachHang;
import com.qlbh.model.NhaCungCap;
import com.qlbh.model.SanPham;
import java.util.ArrayList;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author HoangDucTung
 */
public class TimKiemThongKeJPanel extends javax.swing.JPanel {

    /**
     * Creates new form TimKiemThongKeJPanel
     */
    ImageIcon sai = new ImageIcon("tinhsai.png");
    ImageIcon dung = new ImageIcon("dau-check.png");
    DefaultTableModel ketQuaTableModel;
    DefaultTableModel ketQuaThongKeSoLuongTableModel;

    public TimKiemThongKeJPanel(String username) {
        initComponents();
        ketQuaTableModel = (DefaultTableModel) timKiemjTable.getModel();
        ketQuaThongKeSoLuongTableModel = (DefaultTableModel) thongKejTable.getModel();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        timKiemjTable = new javax.swing.JTable();
        tuKhoaTimKiemjLabel = new javax.swing.JLabel();
        tuKhoaTimKiemjTextField = new javax.swing.JTextField();
        loaiTimKiemjComboBox = new javax.swing.JComboBox<>();
        loaTimKiemjLabel = new javax.swing.JLabel();
        thuocTimKiemjLabel = new javax.swing.JLabel();
        thuocTimKiemjComboBox = new javax.swing.JComboBox<>();
        timKiemjButton = new javax.swing.JButton();
        xuatTiemKiemjButton = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        tuKhoaThongKejLabel = new javax.swing.JLabel();
        thangThongKejLabel = new javax.swing.JLabel();
        thangThongKejComboBox = new javax.swing.JComboBox<>();
        xemThangThongKejButton = new javax.swing.JButton();
        xemSPThongKejButton = new javax.swing.JButton();
        soLuongThongKejTextField = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        thongKejTable = new javax.swing.JTable();
        xuatThongKejButton = new javax.swing.JButton();

        setBackground(new java.awt.Color(0, 102, 102));

        jLabel1.setFont(new java.awt.Font("Arial", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("TÌM KIẾM VÀ THỐNG KÊ");

        timKiemjTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(timKiemjTable);

        tuKhoaTimKiemjLabel.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        tuKhoaTimKiemjLabel.setForeground(new java.awt.Color(0, 102, 102));
        tuKhoaTimKiemjLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/qlbh/images/key.png"))); // NOI18N
        tuKhoaTimKiemjLabel.setText("Từ khóa");

        loaiTimKiemjComboBox.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        loaiTimKiemjComboBox.setForeground(new java.awt.Color(0, 102, 102));
        loaiTimKiemjComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { " ", "Mã", "Tên" }));
        loaiTimKiemjComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loaiTimKiemjComboBoxActionPerformed(evt);
            }
        });

        loaTimKiemjLabel.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        loaTimKiemjLabel.setForeground(new java.awt.Color(0, 102, 102));
        loaTimKiemjLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/qlbh/images/list.png"))); // NOI18N
        loaTimKiemjLabel.setText("Loại");

        thuocTimKiemjLabel.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        thuocTimKiemjLabel.setForeground(new java.awt.Color(0, 102, 102));
        thuocTimKiemjLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/qlbh/images/diagram.png"))); // NOI18N
        thuocTimKiemjLabel.setText("Thuộc");

        thuocTimKiemjComboBox.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        thuocTimKiemjComboBox.setForeground(new java.awt.Color(0, 102, 102));
        thuocTimKiemjComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { " ", "Sản phẩm", "Nhà cung cấp", "Khách hàng" }));
        thuocTimKiemjComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                thuocTimKiemjComboBoxActionPerformed(evt);
            }
        });

        timKiemjButton.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        timKiemjButton.setForeground(new java.awt.Color(0, 102, 102));
        timKiemjButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/qlbh/images/search.png"))); // NOI18N
        timKiemjButton.setText("TÌM");
        timKiemjButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                timKiemjButtonActionPerformed(evt);
            }
        });

        xuatTiemKiemjButton.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        xuatTiemKiemjButton.setForeground(new java.awt.Color(0, 102, 102));
        xuatTiemKiemjButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/qlbh/images/share.png"))); // NOI18N
        xuatTiemKiemjButton.setText("XUẤT");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(xuatTiemKiemjButton, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(loaTimKiemjLabel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(tuKhoaTimKiemjLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 161, Short.MAX_VALUE))
                        .addGap(39, 39, 39)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(loaiTimKiemjComboBox, 0, 126, Short.MAX_VALUE)
                                .addGap(83, 83, 83)
                                .addComponent(thuocTimKiemjLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 134, Short.MAX_VALUE)
                                .addGap(26, 26, 26)
                                .addComponent(thuocTimKiemjComboBox, 0, 201, Short.MAX_VALUE))
                            .addComponent(tuKhoaTimKiemjTextField))
                        .addGap(96, 96, 96)
                        .addComponent(timKiemjButton, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(225, 225, 225)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(71, 71, 71)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tuKhoaTimKiemjTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tuKhoaTimKiemjLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(32, 32, 32)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(loaTimKiemjLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(loaiTimKiemjComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(thuocTimKiemjLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(thuocTimKiemjComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(46, 46, 46))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(timKiemjButton, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(81, 81, 81)))
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 374, Short.MAX_VALUE)
                .addGap(27, 27, 27)
                .addComponent(xuatTiemKiemjButton, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24))
        );

        jTabbedPane1.addTab("Tìm kiếm", jPanel1);

        tuKhoaThongKejLabel.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        tuKhoaThongKejLabel.setForeground(new java.awt.Color(0, 102, 102));
        tuKhoaThongKejLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/qlbh/images/key.png"))); // NOI18N
        tuKhoaThongKejLabel.setText("Từ khóa");

        thangThongKejLabel.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        thangThongKejLabel.setForeground(new java.awt.Color(0, 102, 102));
        thangThongKejLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/qlbh/images/weekly-calendar.png"))); // NOI18N
        thangThongKejLabel.setText("Chọn tháng");

        thangThongKejComboBox.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        thangThongKejComboBox.setForeground(new java.awt.Color(0, 102, 102));
        thangThongKejComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { " ", "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12" }));

        xemThangThongKejButton.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        xemThangThongKejButton.setForeground(new java.awt.Color(0, 102, 102));
        xemThangThongKejButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/qlbh/images/hunter.png"))); // NOI18N
        xemThangThongKejButton.setText("Xem");
        xemThangThongKejButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                xemThangThongKejButtonActionPerformed(evt);
            }
        });

        xemSPThongKejButton.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        xemSPThongKejButton.setForeground(new java.awt.Color(0, 102, 102));
        xemSPThongKejButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/qlbh/images/hunter.png"))); // NOI18N
        xemSPThongKejButton.setText("Xem");
        xemSPThongKejButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                xemSPThongKejButtonActionPerformed(evt);
            }
        });

        soLuongThongKejTextField.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        soLuongThongKejTextField.setForeground(new java.awt.Color(0, 102, 102));

        thongKejTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane2.setViewportView(thongKejTable);

        xuatThongKejButton.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        xuatThongKejButton.setForeground(new java.awt.Color(0, 102, 102));
        xuatThongKejButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/qlbh/images/share.png"))); // NOI18N
        xuatThongKejButton.setText("XUẤT");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jScrollPane2)
                        .addContainerGap())
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(0, 315, Short.MAX_VALUE)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tuKhoaThongKejLabel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(thangThongKejLabel, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addGap(50, 50, 50)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(soLuongThongKejTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 238, Short.MAX_VALUE)
                            .addComponent(thangThongKejComboBox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(190, 190, 190)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(xemSPThongKejButton, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE)
                            .addComponent(xemThangThongKejButton, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE))
                        .addGap(175, 175, 175))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(xuatThongKejButton, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(56, 56, 56)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(xemSPThongKejButton, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(soLuongThongKejTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tuKhoaThongKejLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(4, 4, 4)))
                .addGap(47, 47, 47)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(thangThongKejLabel)
                    .addComponent(thangThongKejComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(xemThangThongKejButton, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(44, 44, 44)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 363, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(xuatThongKejButton, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jTabbedPane1.addTab("Thống kê", jPanel2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jTabbedPane1)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTabbedPane1)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void loaiTimKiemjComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loaiTimKiemjComboBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_loaiTimKiemjComboBoxActionPerformed

    private void thuocTimKiemjComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_thuocTimKiemjComboBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_thuocTimKiemjComboBoxActionPerformed

    private void timKiemjButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_timKiemjButtonActionPerformed
        // TODO add your handling code here:
        try {
            ketQuaTableModel.setRowCount(0);
            String tuKhoa = tuKhoaTimKiemjTextField.getText();
            String loaiTimKiem = loaiTimKiemjComboBox.getSelectedItem().toString();
            String thuocTimKiem = thuocTimKiemjComboBox.getSelectedItem().toString();
            if (tuKhoa.equals("") || loaiTimKiem.equals(" ") || thuocTimKiem.equals(" ")) {
                JOptionPane.showMessageDialog(null, "Vui lòng chọn đầy đủ thông tin để tìm", "Message", JOptionPane.INFORMATION_MESSAGE, sai);

            } else {
                if (loaiTimKiem.equals("Mã")) {
                    switch (thuocTimKiem) {
                        case "Sản phẩm":
                            ArrayList<SanPham> listSP = SanPhamDAO.timKiemSanPhamTheoMa(tuKhoa);
                            String[] colSP = {"STT", "Mã sản phẩn", "Tên sản phẩm", "Số lượng", "Đơn giá", "Mã nhà cung cấp", "Mã nhân viên"};
                            ketQuaTableModel.setColumnIdentifiers(colSP);
                            for (int i = 0; i < listSP.size(); i++) {
                                ketQuaTableModel.addRow(new Object[]{
                                    i + 1,
                                    listSP.get(i).getMaSanPham(),
                                    listSP.get(i).getTenSanPham(),
                                    listSP.get(i).getSoLuong(),
                                    listSP.get(i).getDonGia(),
                                    listSP.get(i).getMaNhaCungCapSP(),
                                    listSP.get(i).getMaNhanVienSP(),});
                            }
                            break;
                        case "Nhà cung cấp":
                            ArrayList<NhaCungCap> listNCC = NhaCungCapDAO.timKiemNhaCungCapTheoMa(tuKhoa);
                            String[] colNCC = {"STT", "Mã nhà cung cấp", "Tên nhà cung cấp", "Địa chỉ", "Email", "Số điện thoại"};
                            ketQuaTableModel.setColumnIdentifiers(colNCC);
                            for (int i = 0; i < listNCC.size(); i++) {
                                ketQuaTableModel.addRow(new Object[]{
                                    i + 1,
                                    listNCC.get(i).getMaNhaCungCap(),
                                    listNCC.get(i).getTenNhaCungCap(),
                                    listNCC.get(i).getDiaChiNhaCungCap(),
                                    listNCC.get(i).getEmailNhaCungCap(),
                                    listNCC.get(i).getSoDienThoaiNCC(),});
                            }
                            break;
                        case "Khách hàng":
                            ArrayList<KhachHang> listKH = KhachHangDAO.timKiemKhachHangTheoMa(tuKhoa);
                            String[] colKH = {"STT", "Mã khách hàng", "Tên khách hàng", "Email", "Địa chỉ", "Số điện thoại"};
                            ketQuaTableModel.setColumnIdentifiers(colKH);
                            for (int i = 0; i < listKH.size(); i++) {
                                ketQuaTableModel.addRow(new Object[]{
                                    i + 1,
                                    listKH.get(i).getMaKhachHang(),
                                    listKH.get(i).getTenKhachHang(),
                                    listKH.get(i).getEmailKhachHang(),
                                    listKH.get(i).getDiaChiKhachHang(),
                                    listKH.get(i).getSoDienThoaiKH(),});
                            }
                            break;
                        default:
                            break;
                    }
                } else {

                    switch (thuocTimKiem) {
                        case "Sản phẩm":
                            ArrayList<SanPham> listSP = SanPhamDAO.timKiemSanPhamTheoTen(tuKhoa);
                            String[] colSP = {"STT", "Mã sản phẩn", "Tên sản phẩm", "Số lượng", "Đơn giá", "Mã nhà cung cấp", "Mã nhân viên"};
                            ketQuaTableModel.setColumnIdentifiers(colSP);
                            for (int i = 0; i < listSP.size(); i++) {
                                ketQuaTableModel.addRow(new Object[]{
                                    i + 1,
                                    listSP.get(i).getMaSanPham(),
                                    listSP.get(i).getTenSanPham(),
                                    listSP.get(i).getSoLuong(),
                                    listSP.get(i).getDonGia(),
                                    listSP.get(i).getMaNhaCungCapSP(),
                                    listSP.get(i).getMaNhanVienSP(),});
                            }
                            break;
                        case "Nhà cung cấp":
                            ArrayList<NhaCungCap> listNCC = NhaCungCapDAO.timKiemNhaCungCapTheoTen(tuKhoa);
                            String[] colNCC = {"STT", "Mã nhà cung cấp", "Tên nhà cung cấp", "Địa chỉ", "Email", "Số điện thoại"};
                            ketQuaTableModel.setColumnIdentifiers(colNCC);
                            for (int i = 0; i < listNCC.size(); i++) {
                                ketQuaTableModel.addRow(new Object[]{
                                    i + 1,
                                    listNCC.get(i).getMaNhaCungCap(),
                                    listNCC.get(i).getTenNhaCungCap(),
                                    listNCC.get(i).getDiaChiNhaCungCap(),
                                    listNCC.get(i).getEmailNhaCungCap(),
                                    listNCC.get(i).getSoDienThoaiNCC(),});
                            }
                            break;
                        case "Khách hàng":
                            ArrayList<KhachHang> listKH = KhachHangDAO.timKiemKhachHangTheoTen(tuKhoa);
                            String[] colKH = {"STT", "Mã khách hàng", "Tên khách hàng", "Email", "Địa chỉ", "Số điện thoại"};
                            ketQuaTableModel.setColumnIdentifiers(colKH);
                            for (int i = 0; i < listKH.size(); i++) {
                                ketQuaTableModel.addRow(new Object[]{
                                    i + 1,
                                    listKH.get(i).getMaKhachHang(),
                                    listKH.get(i).getTenKhachHang(),
                                    listKH.get(i).getEmailKhachHang(),
                                    listKH.get(i).getDiaChiKhachHang(),
                                    listKH.get(i).getSoDienThoaiKH(),});
                            }
                            break;
                        default:
                            break;
                    }
                }

                if (ketQuaTableModel.getRowCount() == 0) {
                    String[] col = {};
                    ketQuaTableModel.setColumnIdentifiers(col);
                    JOptionPane.showMessageDialog(null, "Không tìm thấy kết quả", "Message", JOptionPane.INFORMATION_MESSAGE, sai);

                }
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Kiểm tra giá trị nhập vào", "Message", JOptionPane.INFORMATION_MESSAGE, sai);
        }
    }//GEN-LAST:event_timKiemjButtonActionPerformed

    private void xemSPThongKejButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_xemSPThongKejButtonActionPerformed
        // TODO add your handling code here:
        try {
            ketQuaThongKeSoLuongTableModel.setRowCount(0);
            int soLuong = Integer.parseInt(soLuongThongKejTextField.getText());
            if (soLuong <= 0) {
                JOptionPane.showMessageDialog(null, "Số lượng phải lớn hơn 0", "Message", JOptionPane.INFORMATION_MESSAGE, sai);
            } else {
                ArrayList<SanPham> listSP = SanPhamDAO.locSanPhamTheoSoLuong(soLuong);
                String[] colSP = {"STT", "Mã sản phẩn", "Tên sản phẩm", "Số lượng", "Đơn giá", "Mã nhà cung cấp", "Mã nhân viên"};
                ketQuaThongKeSoLuongTableModel.setColumnIdentifiers(colSP);
                for (int i = 0; i < listSP.size(); i++) {
                    ketQuaThongKeSoLuongTableModel.addRow(new Object[]{
                        i + 1,
                        listSP.get(i).getMaSanPham(),
                        listSP.get(i).getTenSanPham(),
                        listSP.get(i).getSoLuong(),
                        listSP.get(i).getDonGia(),
                        listSP.get(i).getMaNhaCungCapSP(),
                        listSP.get(i).getMaNhanVienSP(),});
                }
                if (ketQuaThongKeSoLuongTableModel.getRowCount() == 0) {
                    String[] col = {};
                    ketQuaThongKeSoLuongTableModel.setColumnIdentifiers(col);
                    JOptionPane.showMessageDialog(null, "Không có sản phẩm nào trong khoảng này", "Message", JOptionPane.INFORMATION_MESSAGE, sai);

                }
            }

        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Kiểm tra giá trị nhập vào", "Message", JOptionPane.INFORMATION_MESSAGE, sai);
        }
    }//GEN-LAST:event_xemSPThongKejButtonActionPerformed

    private void xemThangThongKejButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_xemThangThongKejButtonActionPerformed
        // TODO add your handling code here:
        String thang = thangThongKejComboBox.getSelectedItem().toString();
        if (thang.equals(" ")) {
            JOptionPane.showMessageDialog(null, "Chọn tháng để xem", "Message", JOptionPane.INFORMATION_MESSAGE, sai);
        }
        try {
            int thangSo = Integer.parseInt(thang);
            
        } catch (Exception e) {
            
        }

    }//GEN-LAST:event_xemThangThongKejButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JLabel loaTimKiemjLabel;
    private javax.swing.JComboBox<String> loaiTimKiemjComboBox;
    private javax.swing.JTextField soLuongThongKejTextField;
    private javax.swing.JComboBox<String> thangThongKejComboBox;
    private javax.swing.JLabel thangThongKejLabel;
    private javax.swing.JTable thongKejTable;
    private javax.swing.JComboBox<String> thuocTimKiemjComboBox;
    private javax.swing.JLabel thuocTimKiemjLabel;
    private javax.swing.JButton timKiemjButton;
    private javax.swing.JTable timKiemjTable;
    private javax.swing.JLabel tuKhoaThongKejLabel;
    private javax.swing.JLabel tuKhoaTimKiemjLabel;
    private javax.swing.JTextField tuKhoaTimKiemjTextField;
    private javax.swing.JButton xemSPThongKejButton;
    private javax.swing.JButton xemThangThongKejButton;
    private javax.swing.JButton xuatThongKejButton;
    private javax.swing.JButton xuatTiemKiemjButton;
    // End of variables declaration//GEN-END:variables
}
